# Generated by Django 2.2.5 on 2019-10-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20191023_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='content',
            field=models.CharField(max_length=555, unique=True),
        ),
    ]
