# Generated by Django 2.2.5 on 2019-10-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20191023_1809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
